# prometheus-values.yaml
# ─────────────────────────────────────────────────────────────
# kube-prometheus-stack values for *GKE Autopilot* + Grafana Cloud
# ─────────────────────────────────────────────────────────────

# 1. Autopilot guard-rails ───────────────────────────────────
prometheusOperator:
  admissionWebhooks:
    enabled: false          # no Service in kube-system
    patch:
      enabled: false        # no patch Job in kube-system
  tls:
    enabled: false

nodeExporter:
  enabled: false            # hostPID / hostPath → forbidden

kubeControllerManager:
  enabled: false
  service:
    enabled: false
kubeScheduler:
  enabled: false
  service:
    enabled: false
kubeProxy:
  enabled: false
  service:
    enabled: false
kubeEtcd:
  enabled: false
  service:
    enabled: false
coreDns:
  enabled: false
  service:
    enabled: false

# 2. Grafana UI inside cluster (optional) ─────────────────────
grafana:
  enabled: true
  admin:
    existingSecret: grafana-cloud
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests:
      cpu: 200m
      memory: 400Mi

# 3. Alertmanager resource knobs ─────────────────────────────
alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 150Mi

# 4. Prometheus server settings + remote-write ───────────────
prometheus:
  service:
    type: ClusterIP          # internal only; no LoadBalancer
  prometheusSpec:
    # keep Helm selectors
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues:    false

    retention: 10d

    resources:
      requests:
        cpu: 200m
        memory: 500Mi

    # Push metrics to Grafana Cloud
    remoteWrite:
      - url: "https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push"
        basicAuth:
          username:
            name: grafana-cloud   # ← Secret you’ll create once
            key:  username
          password:
            name: grafana-cloud
            key:  password
