apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-elastic-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # The password must be base64 encoded for Kubernetes secrets
  password: {{ .Values.connections.elasticPassword | b64enc | quote }} 