services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: intern
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  temporal:
    image: temporalio/auto-setup:1.24
    depends_on: [postgres]
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: dev
      POSTGRES_PWD: dev
      POSTGRES_SEEDS: postgres
      # ← remove the bad path; if you *really* want to set it, use one of:
      # DYNAMIC_CONFIG_FILE_PATH: /etc/temporal/config/dynamicconfig
      # DYNAMIC_CONFIG_FILE_PATH: /etc/temporal/config/dynamicconfig/docker.yaml
    ports: ["7233:7233"]

  temporal-web:
    image: temporalio/ui:2.39.0
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_DEFAULT_NAMESPACE: default
    ports: ["8088:8080"]
    depends_on: [temporal]

volumes:
  postgres_data:
